//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConnectDBRequest : DbContext
    {
        public ConnectDBRequest()
            : base("name=ConnectDBRequest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Defect> Defect { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<View_All_Request> View_All_Request { get; set; }
    
        public virtual ObjectResult<GetRequestMasterName_Result> GetRequestMasterName(string masterName)
        {
            var masterNameParameter = masterName != null ?
                new ObjectParameter("MasterName", masterName) :
                new ObjectParameter("MasterName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestMasterName_Result>("GetRequestMasterName", masterNameParameter);
        }
    
        public virtual ObjectResult<GetRequestMasterNameLike_Result> GetRequestMasterNameLike(string masterNameLike)
        {
            var masterNameLikeParameter = masterNameLike != null ?
                new ObjectParameter("MasterNameLike", masterNameLike) :
                new ObjectParameter("MasterNameLike", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestMasterNameLike_Result>("GetRequestMasterNameLike", masterNameLikeParameter);
        }
    }
}
