//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequestDeviceId { get; set; }
        public int RequestDefectId { get; set; }
        public int RequestClientId { get; set; }
        public string RequestDescription { get; set; }
        public int RequestStatusId { get; set; }
        public int RequestMasterId { get; set; }
        public int RequestTime { get; set; }
        public int RequestPriorirtyId { get; set; }
        public int RequestStageId { get; set; }
        public string RequestComment { get; set; }
    
        public virtual Defect Defect { get; set; }
        public virtual Device Device { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
